default: styles/qoto.scss
qoto-no-ticker: styles/qoto-no-ticker.scss
contrast: styles/contrast.scss
mask: styles/mask.scss
mastodon-light: styles/mastodon-light.scss
mobile-small: styles/mobile-small.scss
instance-ticker-type-0: styles/instance-ticker-type-0.scss
instance-ticker-type-1: styles/instance-ticker-type-1.scss
instance-ticker-type-2: styles/instance-ticker-type-2.scss
instance-ticker-type-10: styles/instance-ticker-type-10.scss
instance-ticker-type-11: styles/instance-ticker-type-11.scss
instance-ticker-type-12: styles/instance-ticker-type-12.scss
instance-ticker-type-0-contrast: styles/instance-ticker-type-0-contrast.scss
instance-ticker-type-1-contrast: styles/instance-ticker-type-1-contrast.scss
instance-ticker-type-2-contrast: styles/instance-ticker-type-2-contrast.scss
instance-ticker-type-10-contrast: styles/instance-ticker-type-10-contrast.scss
instance-ticker-type-11-contrast: styles/instance-ticker-type-11-contrast.scss
instance-ticker-type-12-contrast: styles/instance-ticker-type-12-contrast.scss
instance-ticker-type-0-light: styles/instance-ticker-type-0-light.scss
instance-ticker-type-1-light: styles/instance-ticker-type-1-light.scss
instance-ticker-type-2-light: styles/instance-ticker-type-2-light.scss
instance-ticker-type-10-light: styles/instance-ticker-type-10-light.scss
instance-ticker-type-11-light: styles/instance-ticker-type-11-light.scss
instance-ticker-type-12-light: styles/instance-ticker-type-12-light.scss
missing: styles/missing.scss
missing-contrast: styles/missing-contrast.scss
missing-light: styles/missing-light.scss
mastodon: styles/application.scss
blue: styles/blue.scss
mastoblue: styles/mastoblue.scss
material-light: styles/material-light.scss
material-dark: styles/material-dark.scss
mastodon-wide-light: styles/mastodon-wide-light.scss
mastodon-wide-dark: styles/mastodon-wide-dark.scss
